image: continuumio/miniconda3:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - conda env create -f environment.yml
  - source activate revealjs
  - pandoc --version

test:
  script:
    - make

pages:
  stage: deploy
  script:
    - make all
    - make full
  artifacts:
    paths:
      - public
