image: continuumio/miniconda3:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

jupyter-build:
  stage: build
  before_script:
    - conda env create -f environment.yml
    - source activate comp2421-book

  script:
    # - jupyter-book build . --builder linkcheck TODO make this pass
    - jupyter-book clean .
    - jupyter-book build .
  artifacts:
    paths:
      - _build/

pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv _build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
