image: continuumio/miniconda3:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - conda env create -f environment.yml
  - source activate comp2421
  - pandoc --version
  - apt-get update -qq
  - apt-get install -y texlive texlive-plain-generic texlive-pictures librsvg2-bin
  - pdflatex --version

test:
  script:
    - make all
    - make test

pages:
  stage: deploy
  script:
    - make all
    - make build
  artifacts:
    paths:
      - public
