image: continuumio/miniconda3:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - conda env create -f environment.yml
  - source activate revealjs
  - pandoc --version
  - apt-get update -qq
  - apt-get install -y texlive texlive-plain-generic texlive-recommended
  - pdflatex --version

test:
  script:
    - make

pages:
  stage: deploy
  script:
    - make all
    - make build
  artifacts:
    paths:
      - public
