image: continuumio/miniconda3:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

jupyter-build:
  stage: build
  before_script:
    - conda env create -f environment.yml
    - source activate comp2421-book
    # - pandoc --version
    # - apt-get update -qq
    # - apt-get install -y texlive texlive-plain-generic texlive-pictures librsvg2-bin
    # - pdflatex --version

  script:
    - jupyter-book build . --builder linkcheck
    - jupyter-book clean .
    - jupyter-book build .
  artifacts:
    paths:
      - _build/

pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv _build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
