image: mambaorg/micromamba:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

jupyter-build:
  stage: build
  before_script:
    - micromamba install -y -n base -f environment.yml

  script:
    # - jupyter-book build . --builder linkcheck TODO make this pass
    - jupyter-book clean .
    - jupyter-book build .
    - python _convert.py
  artifacts:
    paths:
      - _build/

pages:
  stage: deploy
  image: busybox:latest
  script:
    - mv _build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
