name: comp2421-book
channels:
  - conda-forge
  - defaults
dependencies:
  # socs machine default versions
  - python = 3.12
  - jupyterlab = 4.0
  - matplotlib = 3.8
  - numpy = 1.26
  - scipy = 1.13
  - pandas = 2.2
  # for building the book
  - jupyter-book = 0.15
  - make = 4.3
  - git = 2.38
  - git-lfs = 3.2
  # for making slides
  - pandoc = 3.4
  # additional packages used in the book
  - xlrd = 2.0
  - qrcode = 7.3
  - ffmpeg = 5.1
  # for help making the book
  - livereload = 2.6
  - black = 24.8
  - ruff = 0.6
  - nbqa = 1.6
  - blacken-docs = 1.12
  - pre-commit = 3.4
