name: deploy

on:
  # Trigger the deploy on push to main branch
  push:
    branches:
      - main
      - 2023
  # Trigger the deploy on pull requests to main branch
  pull_request:
    branches:
      - main

jobs:
  # This job deploys the example book
  test-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install conda environment from environment.yml
      uses: mamba-org/provision-with-micromamba@main

    - name: Notebook formatting
      shell: bash -l {0}
      run: |
        black --check .
        nbqa black --check .
        nbqa blacken-docs . --nbqa-md

    - name: Test links
      shell: bash -l {0}
      run: |
        jupyter-book build . --builder linkcheck

    - name: Test worksheet solutions
      shell: bash -l {0}
      run: |
        jupyter nbconvert --clear-output --to notebook --inplace ws/*implemented.ipynb
        jupyter execute ws/*implemented.ipynb

    # Build the example book
    - name: Build book
      shell: bash -l {0}
      run: |
        jupyter-book build .

  # This job deploys the example book on success of tests
  deploy-book:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install conda environment from environment.yml
      uses: mamba-org/provision-with-micromamba@main

    # Build the example book
    - name: Build book
      shell: bash -l {0}
      run: |
        jupyter-book build .

    # Deploy html to gh-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
